[build]
	command = "cd .. && npm install && cd fe && npm run build"
	publish = ".svelte-kit/netlify"

[build.environment]
	ADAPTER = "netlify"
	NODE_VERSION = "18.13.0"
	VITE_BE_ENV = "dev"

[functions]
	# temporary workaround for https://github.com/sveltejs/kit/issues/6462
	node_bundler = "esbuild"

[context.dev.environment]
	VITE_BE_ENV = "dev"

[context.staging.environment]
	VITE_BE_ENV = "staging"

[context.production.environment]
	VITE_BE_ENV = "production"

# re: `VITE_BE_ENV` please see `fe/src/lib/env.js`
